
sudo: required

services:
  - docker

env:
  matrix:
    - OS=centos DIST=7 PACKAGE=aria2

install:
  - scripts/install.sh

script:
  - scripts/build.sh

deploy:
  provider: script
  script: scripts/deploy.sh
