---

sudo: required
dist: trusty

services:
  - docker

env:
  matrix:
    - OS=centos DIST=8 PACKAGE=aria2
    - OS=centos DIST=8 PACKAGE=tmux
    - OS=centos DIST=7 PACKAGE=aria2
    - OS=centos DIST=7 PACKAGE=tmux
    - OS=centos DIST=6 PACKAGE=tmux
    - OS=ol DIST=8 PACKAGE=aria2
    - OS=ol DIST=8 PACKAGE=tmux
    - OS=ol DIST=7 PACKAGE=aria2
    - OS=ol DIST=7 PACKAGE=tmux
    - OS=ol DIST=6 PACKAGE=tmux
    # - OS=centos DIST=7 PACKAGE=node_exporter
    # - OS=centos DIST=6 PACKAGE=node_exporter
    # - OS=ol DIST=7 PACKAGE=node_exporter
    # - OS=ol DIST=6 PACKAGE=node_exporter

install:
  - scripts/install.sh

script:
  - scripts/build.sh

deploy:
  provider: script
  script: scripts/deploy.sh
