---

sudo: required
dist: trusty

services:
  - docker

env:
  matrix:
    - OS=centos DIST=7 PACKAGE=aria2
    - OS=centos DIST=7 PACKAGE=tmux
    - OS=ol DIST=7 PACKAGE=aria2
    - OS=ol DIST=7 PACKAGE=tmux

install:
  - scripts/install.sh

script:
  - scripts/build.sh

deploy:
  provider: script
  script: scripts/deploy.sh
